use kdl_config::merge::PartialConfig;
use kdl_config::{Kdl, KdlMerge, KdlPartial};

#[derive(Clone, Default, Debug, PartialEq, Kdl, KdlMerge, KdlPartial)]
struct Agentic {
    #[kdl(attr)]
    max_calls: u32,
}

#[derive(Clone, Default, Debug, PartialEq, Kdl, KdlMerge, KdlPartial)]
struct Answer {
    #[kdl(attr)]
    provider: String,
    #[kdl(attr)]
    model: String,
    #[kdl(child)]
    agentic: Agentic,
}

// The partial mirror (`AnswerPartial`, `AgenticPartial`) is generated by
// `#[derive(KdlPartial)]` — no hand-written mirror, no `partial_for`.

#[test]
fn nested_subfield_non_clobber() {
    let base = Answer {
        provider: "template".into(),
        model: "m".into(),
        agentic: Agentic { max_calls: 8 },
    };
    // A layer fragment that sets ONLY provider.
    let p: AnswerPartial = kdl_config::parse_str("answer provider=\"openai\"").unwrap();
    let out = p.apply_to(base);
    assert_eq!(out.provider, "openai"); // overridden
    assert_eq!(out.model, "m"); // sibling preserved
    assert_eq!(out.agentic.max_calls, 8); // nested preserved
}

#[test]
fn nested_child_subfield_merges() {
    let base = Answer {
        provider: "template".into(),
        model: "m".into(),
        agentic: Agentic { max_calls: 8 },
    };
    let p: AnswerPartial = kdl_config::parse_str("answer { agentic max_calls=99 }").unwrap();
    let out = p.apply_to(base);
    assert_eq!(out.provider, "template"); // untouched
    assert_eq!(out.agentic.max_calls, 99); // nested override
}

// --- Richer shapes: combined Kdl + KdlMerge + KdlPartial with merge/partial
// attrs (exercises the parser tolerating `merge`/`partial` on a `Kdl` struct). ---

#[derive(Clone, Default, Debug, PartialEq, kdl_config::KdlValue, KdlMerge)]
enum Level {
    #[default]
    Low,
    High,
}

#[derive(Clone, Default, Debug, PartialEq, Kdl, KdlMerge, KdlPartial)]
struct Sub {
    #[kdl(attr)]
    x: u32,
    #[kdl(attr)]
    y: u32,
}

#[derive(Clone, Default, Debug, PartialEq, Kdl, KdlMerge, KdlPartial)]
struct Cfg {
    #[kdl(attr, scalar)]
    level: Level, // enum-as-attr -> leaf Option<Level> (replace)
    #[kdl(attr)]
    timeout: Option<u64>, // already-Option value -> leaf, deep-merge
    #[kdl(child)]
    sub: Sub, // recurse -> sub-field-granular
    #[kdl(child, partial = "whole")]
    whole_sub: Sub, // forced leaf -> whole-struct override
    #[kdl(value, merge = "append")]
    tags: Vec<String>, // append across layers
    #[kdl(skip)]
    derived: u32, // omitted from partial, kept via ..base
}

#[test]
fn append_skip_whole_enum_optionvalue_merge_law() {
    let base = Cfg {
        level: Level::Low,
        timeout: Some(5),
        sub: Sub { x: 1, y: 2 },
        whole_sub: Sub { x: 10, y: 20 },
        tags: vec!["a".into()],
        derived: 99,
    };
    let p = CfgPartial {
        level: Some(Level::High),
        timeout: Some(7),
        sub: Some(SubPartial {
            x: Some(100),
            y: None,
        }),
        whole_sub: Some(Sub { x: 0, y: 0 }),
        tags: vec!["b".into()],
    };
    let out = p.apply_to(base);
    assert_eq!(out.level, Level::High); // enum replace
    assert_eq!(out.timeout, Some(7)); // option-value override
    assert_eq!(out.sub, Sub { x: 100, y: 2 }); // recurse: x over, y preserved
    assert_eq!(out.whole_sub, Sub { x: 0, y: 0 }); // whole override
    assert_eq!(out.tags, vec!["a".to_string(), "b".to_string()]); // append
    assert_eq!(out.derived, 99); // skip kept from base
}

// --- Flatten recurses (sub-field granularity through an inlined struct). ---

#[derive(Clone, Default, Debug, PartialEq, Kdl, KdlMerge, KdlPartial)]
struct Inner {
    #[kdl(attr)]
    a: u32,
    #[kdl(attr)]
    b: u32,
}

#[derive(Clone, Default, Debug, PartialEq, Kdl, KdlMerge, KdlPartial)]
struct Outer {
    #[kdl(flatten)]
    inner: Inner,
    #[kdl(attr)]
    name: String,
}

#[test]
fn flatten_recurses_subfield() {
    let base = Outer {
        inner: Inner { a: 1, b: 2 },
        name: "n".into(),
    };
    let p: OuterPartial = kdl_config::parse_str("outer a=9").unwrap();
    let out = p.apply_to(base);
    assert_eq!(out.inner.a, 9); // flattened attr override
    assert_eq!(out.inner.b, 2); // sub-field preserved (flatten recurse, not whole-replace)
    assert_eq!(out.name, "n"); // untouched
}

// --- rename_all is carried onto the generated partial (field-key parity). ---

#[derive(Clone, Default, Debug, PartialEq, Kdl, KdlMerge, KdlPartial)]
#[kdl(rename_all = "kebab-case")]
struct Renamed {
    #[kdl(attr)]
    max_count: u32,
    #[kdl(attr)]
    base_url: String,
}

#[test]
fn rename_all_carried_to_partial() {
    let base = Renamed {
        max_count: 1,
        base_url: "a".into(),
    };
    // The partial must decode the kebab key `max-count`; if rename_all were not
    // carried it would look for `max_count`, miss it, and leave max_count == 1.
    let p: RenamedPartial = kdl_config::parse_str("renamed max-count=5").unwrap();
    let out = p.apply_to(base);
    assert_eq!(out.max_count, 5);
    assert_eq!(out.base_url, "a");
}

#[test]
fn absent_root_is_identity() {
    let base = Answer {
        provider: "p".into(),
        model: "m".into(),
        agentic: Agentic { max_calls: 3 },
    };
    let p: AnswerPartial = kdl_config::parse_str("answer").unwrap();
    assert_eq!(p.apply_to(base.clone()), base);
}
